### ISSUE TITLE
Boxed field of class are copied across all class instances

### ISSUE THREAD

**Issue by davidmz** [sonaye/mobx-box#3]
Please see this [example code](https://codesandbox.io/s/k09lkv1xk3?module=%2Fsrc%2Fbox.test.js&previewwindow=tests).

I expected that the objects 'a' and 'b' will have independent boxed properties 'x'. But this test shows that the property is one for all objects of the class. Is this expected behavior? Maybe I'm doing something wrong?

**Comment by davidmz** [comment]
As far as I understand the docs (https://mobx.js.org/best/decorators.html), `decorate` should apply decorators to class fields/methods. So
```js
class A {
  @box x;
}
```
should have the same effect as
```js
class A {
  x;
}
decorate(A, {x: box});
```
I could, of course, apply decorator in constructor but I would prefer to decorate the class itself.

**Comment by sonaye** [comment]
I don't think that `decorate` supports decorators other than the ones that are provided within mobx. If you look at the source of this library, it uses `computed` and `observable` under the hood, but clearly `decorate` doesn't understand that and breaks things.

Personally I don't recommend that you use decorators at all as it is still a pending proposal (can change), the only reason I haven't [deprecated](https://github.com/sonaye/mobx-apollo/commit/f9f16b9df8228b8dfbe47f23d423e28995e8cdef#commitcomment-25667662) them from this package is that it's been a while since I started a new project on top of mobx (I use context for state management now).
